### ISSUE TITLE
Problem with screen orientation

### ISSUE THREAD

**Issue by pmbnecc** [grantland/android-autofittextview#57]
When I switch the screen from landscape to portrait mode, I get a Null Pointer Exception.  I did not have this problem before adding the me.grantland.widget.AutofitTextView.

01-03 22:35:24.841 17553-17553/com.northeast_cc.plugmyband E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.northeast_cc.plugmyband, PID: 17553
                                                                             java.lang.RuntimeException: Unable to retain activity {com.northeast_cc.plugmyband/com.northeast_cc.plugmyband.PlugMyBand}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.northeast_cc.plugmyband.AsyncTaskManager.retainTask()' on a null object reference
                                                                                 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4840)
                                                                                 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4889)
                                                                                 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5142)
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:205)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6895)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.northeast_cc.plugmyband.AsyncTaskManager.retainTask()' on a null object reference
                                                                                 at com.northeast_cc.plugmyband.PlugMyBand.onRetainNonConfigurationInstance(PlugMyBand.java:711)
                                                                                 at android.app.Activity.retainNonConfigurationInstances(Activity.java:2004)
                                                                                 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4836)
                                                                                 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4889) 
                                                                                 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5142) 
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:205) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6895) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by grantland** [comment]
I do not see this library's package name, `me.grantland.widget` anywhere in this stack trace. Are you sure this isn't due to `com.northeast_cc.plugmyband.AsyncTaskManager`?

**Comment by pmbnecc** [comment]
I apologize.  I tested it without your code, and I still get the null pointer exception.  I have a problem elsewhere.
