### ISSUE TITLE
crash at setcontentview

### ISSUE THREAD

**Issue by gokhantasci** [grantland/android-autofittextview#62]
Autofittextview was working fine till i tried to implement something;
I deleted everything i made, the code is fully same the time it was working.

Please help

04-21 01:54:03.287 7118-7118/com.gor.hocam E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.gor.hocam, PID: 7118
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gor.hocam/com.gor.hocam.MainActivity}: android.view.InflateException: Binary XML file line #56: Error inflating class me.grantland.widget.AutofitTextView
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5139)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: android.view.InflateException: Binary XML file line #56: Error inflating class me.grantland.widget.AutofitTextView
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                 at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:343)
                                                                 at android.app.Activity.setContentView(Activity.java:1929)
                                                                 at com.gor.hocam.MainActivity.onCreate(MainActivity.java:111)
                                                                 at android.app.Activity.performCreate(Activity.java:5231)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5139) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "me.grantland.widget.AutofitTextView" on path: DexPathList[[zip file "/data/app/com.gor.hocam-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.gor.hocam-1, /vendor/lib, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:559)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                 at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:343) 
                                                                 at android.app.Activity.setContentView(Activity.java:1929) 
                                                                 at com.gor.hocam.MainActivity.onCreate(MainActivity.java:111) 
                                                                 at android.app.Activity.performCreate(Activity.java:5231) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5139) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by grantland** [comment]
It looks like the class `AutofitTextView` is missing in your classpath, which leads me to believe you have an error in your project configuration.

**Comment by gokhantasci** [comment]
So what to do to solve this ?
This was working great earlier.

**Comment by grantland** [comment]
It's probably a bad proguard configuration, but I don't know since this is out of the scope of this project.
